��:^<?php exit; ?>a:1:{s:7:"content";a:49:{s:10:"_edit_lock";a:1:{i:0;s:13:"1580224740:30";}s:13:"_thumbnail_id";a:1:{i:0;s:5:"12493";}s:16:"_format_link_url";a:1:{i:0;s:0:"";}s:24:"_format_quote_source_url";a:1:{i:0;s:0:"";}s:25:"_format_quote_source_name";a:1:{i:0;s:0:"";}s:19:"_format_audio_embed";a:1:{i:0;s:0:"";}s:19:"_format_video_embed";a:1:{i:0;s:0:"";}s:10:"_edit_last";a:1:{i:0;s:1:"9";}s:8:"produits";a:1:{i:0;s:1:"3";}s:9:"_produits";a:1:{i:0;s:19:"field_5d8b6efdde49c";}s:29:"_yoast_wpseo_primary_category";a:1:{i:0;s:1:"7";}s:22:"_format_gallery_images";a:1:{i:0;s:22:"a:1:{i:0;s:5:"12493";}";}s:18:"penci_recipe_title";a:1:{i:0;s:36:"Salade d’endives et son chou farci";}s:21:"penci_recipe_servings";a:1:{i:0;s:0:"";}s:21:"penci_recipe_preptime";a:1:{i:0;s:10:"30 minutes";}s:28:"penci_recipe_preptime_format";a:1:{i:0;s:0:"";}s:21:"penci_recipe_cooktime";a:1:{i:0;s:10:"30 minutes";}s:28:"penci_recipe_cooktime_format";a:1:{i:0;s:0:"";}s:25:"penci_recipe_instructions";a:1:{i:0;s:1935:"&lt;p&gt;&lt;em&gt;Pour la salade d’endives :&lt;/em&gt; &lt;br /&gt;Recouvrir le fond du bento avec quelques pousses de mâche. Retirer les premières feuilles de l’endive. Placer les feuilles dans votre bento.&lt;/p&gt;
&lt;p&gt;Découper le chèvre en petits dés.&lt;/p&gt;
&lt;p&gt;Couper la poire en deux dans le sens de la hauteur, l’évider et la couper en fines tranches.&lt;/p&gt;
&lt;p&gt;Ajouter les morceaux de chèvre, les fines tranches de poires et les noix de pécan au cœur des feuilles d’endive. Parsemer votre salade de quelques graines de courge.&lt;/p&gt;
&lt;p&gt;Remplir votre récipient à sauce MB Temple de vinaigre balsamique et huile d’olive pour accompagner votre salade lors de sa dégustation.&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Pour le chou farci :&lt;/em&gt; &lt;br /&gt;Porter une casserole d’eau à ébullition. Blanchir la feuille de chou vert pendant 10 minutes.&lt;/p&gt;
&lt;p&gt;Couper les champignons et la pomme de terre en dés, puis émincer les oignons.&lt;/p&gt;
&lt;p&gt;Dans une casserole faire revenir champignons, pomme de terre et oignon dans l’huile d’olive pendant 10 minutes, puis ajouter la moutarde.&lt;/p&gt;
&lt;p&gt;Étaler la feuille de chou vert dans un plat allant au four, la garnir de la farce obtenue et refermer la feuille de chou en la repliant sur elle-même.&lt;/p&gt;
&lt;p&gt;Cuire à 180°C pendant 20 minutes.&lt;/p&gt;
&lt;p&gt;Pour compléter ce repas, vous pouvez l’accompagner d’une orange et de petits sablés.&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Les astuces zéro déchet :&lt;/strong&gt; &lt;br /&gt;- Garder les écorces d’orange pour faire des orangettes ou une délicieuse marmelade &lt;br /&gt;- Acheter ses légumes en vrac en apportant ses propres contenants &lt;br /&gt;- Opter pour des fruits et légumes BIO pour garder leur peau &lt;br /&gt;- Utiliser les restes de pâte à tarte pour réaliser des sablés !&lt;/p&gt;";}s:24:"penci_recipe_ingredients";a:1:{i:0;s:476:"<p>Ingrédients pour un MB Original : <br />Salade : <br />- Une petite endive <br />- 20g de fromage de chèvre <br />- Quelques pousses de mâche <br />- Une poignée de noix de pécan <br />- Quelques graines de courge <br />- Une poire <br /><br />Chou farci : <br />- 1 grosse feuille de chou vert <br />- 3 champignons de Paris <br />- 1 pomme de terre <br />- ½ oignon <br />- 1 CAC de moutarde <br />- 1 poignée de graine de lin <br />- 1 CAS d’huile d’olive</p>";}s:17:"penci_recipe_note";a:1:{i:0;s:0:"";}s:21:"penci_recipe_calories";a:1:{i:0;s:0:"";}s:16:"penci_recipe_fat";a:1:{i:0;s:0:"";}s:21:"penci_recipe_keywords";a:1:{i:0;s:0:"";}s:20:"penci_recipe_cuisine";a:1:{i:0;s:0:"";}s:20:"penci_recipe_videoid";a:1:{i:0;s:0:"";}s:23:"penci_recipe_videotitle";a:1:{i:0;s:0:"";}s:26:"penci_recipe_videoduration";a:1:{i:0;s:0:"";}s:22:"penci_recipe_videodate";a:1:{i:0;s:0:"";}s:21:"penci_recipe_videodes";a:1:{i:0;s:0:"";}s:33:"penci_custom_sidebar_page_display";a:1:{i:0;s:0:"";}s:26:"penci_post_sidebar_display";a:1:{i:0;s:0:"";}s:18:"penci_single_style";a:1:{i:0;s:0:"";}s:27:"penci_pfeatured_image_ratio";a:1:{i:0;s:0:"";}s:28:"penci_enable_jarallax_single";a:1:{i:0;s:0:"";}s:24:"penci_post_hide_featuimg";a:1:{i:0;s:0:"";}s:26:"_yoast_wpseo_content_score";a:1:{i:0;s:2:"30";}s:22:"penci_post_views_count";a:1:{i:0;s:3:"556";}s:27:"penci_post_week_views_count";a:1:{i:0;s:1:"0";}s:28:"penci_post_month_views_count";a:1:{i:0;s:3:"556";}s:23:"penci_recipe_rate_total";a:1:{i:0;s:1:"5";}s:24:"penci_recipe_rate_people";a:1:{i:0;s:1:"1";}s:12:"_wp_old_date";a:1:{i:0;s:10:"2020-01-21";}s:18:"produits_0_produit";a:1:{i:0;s:5:"12548";}s:19:"_produits_0_produit";a:1:{i:0;s:19:"field_5d8b6f09de49d";}s:18:"produits_1_produit";a:1:{i:0;s:5:"12590";}s:19:"_produits_1_produit";a:1:{i:0;s:19:"field_5d8b6f09de49d";}s:18:"produits_2_produit";a:1:{i:0;s:0:"";}s:19:"_produits_2_produit";a:1:{i:0;s:19:"field_5d8b6f09de49d";}}}