<div class="social-links">
	<ul>
		<li class="addthis_toolbox addthis_default_style addthis_32x32_style addthis-smartlayers addthis-animated at4-show" addthis:title="Blog Monbento - <?php echo $this->getData('postTitle');  ?>" addthis:description="<?php echo $this->getData('postTitle');  ?>" addthis:url="<?php echo rtrim($this->getData('postUrl'), '/');  ?>">
                    <a class="addthis_button_email"></a>
                    <a class="addthis_counter_facebook"></a>
                    <a class="addthis_button_pinterest_share"></a>
                    <a class="addthis_counter_twitter" data-social="twitter"></a>
                    <a class="addthis_button_google_plusone_share" data-social="google+"></a>
                    <a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a>
                    &nbsp;
		</li>
	</ul>
</div>