<?php
/**
 * MageWidget_FeaturedProduct extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   MageWidget
 * @package    MageWidget_FeaturedProduct
 * @copyright  Copyright (c) 2010 Anthony Charrex
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>

<div class="widget-new-products">
  <div class="widget-title">
    <h2<?php echo $this->getCategoryIcon() ?>><?php if( $this->getCategoryLink()): ?><a href="<?php echo $this->getCategoryLink() ?>"><?php endif;?><?php echo $this->htmlEscape($this->getCategoryTitle()) ?><?php if( $this->getCategoryLink()): ?></a><?php endif;?></h2>
  </div>
  <?php if( $this->getCategoryLink()): ?>
  <div class="more"><a href="<?php echo $this->getCategoryLink() ?>" rel="nofollow"><?php echo $this->__('More products') ?></a></div>
  <?php endif;?>
  <div class="widget-products">
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $items = array(); ?>
    <?php foreach ($_products->getItems() as $_product): ?>
    	<?php $this->getProductOrder($_product->getEntityId()) ?>
    	<?php $items[$this->getProductOrder($_product->getEntityId())] = $_product; ?>
    <?php endforeach; ?>
    <?php ksort($items);?>
    <?php $i=0; foreach ($items as $_product): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid">
      <?php endif ?>
      <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
              <img class="hide-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(175) ?>" width="175" height="175" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
              <img class="show-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(400) ?>" width="400" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
          </a>
        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
        <?php echo $this->getPriceHtml($_product, true, '-featuredproduct-grid') ?>
        <div class="actions"><a href="<?php echo $_product->getProductUrl() ?>" class="more" rel="nofollow"><?php echo $this->__('Learn more') ?></a>
          <?php if($_product->isSaleable()): ?>
          <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="btn-cart"><?php echo $this->__('Add') ?></a>
          <?php endif ?>
        </div>
      </li>
      <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
    </ul>
    <?php endif ?>
    <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>
