<?php
/**
 * Product:     Advanced Permissions
 * Package:     Aitoc_Aitpermissions_2.6.2_2.0.3_635589
 * Purchase ID: kvKHKGrR2nArLn9zDhP1NEqsGPa1BPw4KDqhieWQEX
 * Generated:   2013-07-16 07:25:55
 * File path:   app/design/frontend/default/default/template/aitpermissions/lfooter.phtml
 * Copyright:   (c) 2013 AITOC, Inc.
 */
?>
<?php
/**
 * @copyright  Copyright (c) 2009 AITOC, Inc. 
 */
?>
<!-- wpbzdxspkrcglbepuumwvaryiwzbaxhe -->