<?php

$collection = $this->getCollection();

$limits = array(
    10 => 10,
    50 => 50,
    100 => 100
);
$trans = Mage::helper('dbm_share');

$this->setAvailableLimits($limits); 
?>
<?php /* if($collection->count() > $collection->getPageSize()): ?>
<div class="clubListToolbar">
    <div class="perPage">Articles par page <a href="#">10</a> <a href="#">50</a> <a href="#">100</a></div>
    <?php if($collection->getSize()): ?>
    <div class="paginator">
        <ul class="pages">
            <li><a href="#" class="previous"><img src="<?php echo $this->getSkinUrl('images/club/toolbar/previous.png') ?>" alt=""></a></li>
        <?php for($i = 1; $i <= ceil($this->getTotalNum() / $collection->getPageSize()); $i++): ?>
            <li><a href="#"><?php echo $i; ?></a></li>
        <?php endfor; ?>
            <li><a href="#" class="next"><img src="<?php echo $this->getSkinUrl('images/club/toolbar/next.png') ?>" alt=""></a></li>
        </ul>
    </div>
    <?php endif; ?>
</div>
<?php endif; */?>
<div class="clubListToolbar small-12 columns">

<?php if($this->getShowPerPage()): ?>
    <div class="perPage">
        <?php echo $this->__('Articles per page'); ?>
    <?php foreach ($limits as $_key=>$_limit): ?>
            <a href="<?php echo $this->getLimitUrl($_key) ?>" class="<?php if($this->isLimitCurrent($_key)): ?> selected<?php endif ?>"><?php echo $_limit ?></a> 
    <?php endforeach; ?>
    </div>
<?php endif ?>
<?php if($this->getLastPageNum()>1): ?>
<?php if($this->getCollection()->getSize()): ?>
    <div class="paginator">
        <ul class="pages">
        <?php if (!$this->isFirstPage()): ?>
            <li class="first">
                <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                    <?php if(!$this->getAnchorTextForPrevious()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/club/toolbar/previous.png') ?>" alt="<?php echo $this->__('Previous') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForPrevious() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>

        <?php if ($this->canShowFirst()): ?>
            <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a class="previous_jump" title="" href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="current"><?php echo $_page ?></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>


        <?php if ($this->canShowNextJump()): ?>
            <li><a class="next_jump" title="" href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
          <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>

        <?php if (!$this->isLastPage()): ?>
            <li class="last">
                <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                    <?php if(!$this->getAnchorTextForNext()): ?>
                        <img src="<?php echo $this->getSkinUrl('images/club/toolbar/next.png') ?>" alt="<?php echo $this->__('Next') ?>" class="v-middle" />
                    <?php else: ?>
                        <?php echo $this->getAnchorTextForNext() ?>
                    <?php endif;?>
                </a>
            </li>
        <?php endif;?>
        </ul>

    </div>
    <?php endif; ?>
<?php endif ?>



</div>


