<!-- 
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->

<label for="<?php echo $this->getFieldId('iban')?>">
	<?php echo $this->__('IBAN') ?>
</label>
<div class="input-box" >
    <input type="text"
        id="<?php echo $this->getFieldId('iban')?>"
        name="<?php echo $this->getFieldName('iban')?>"
        value="<?php echo $this->htmlEscape($this->getIban()) ?>"
        class="input-text"
        <?php echo $this->getFieldParams() ?> />
</div>
<label for="<?php echo $this->getFieldId('siret')?>">
	<?php echo $this->__('Campany number') ?>
</label>
<div class="input-box" >
    <input type="text"
        id="<?php echo $this->getFieldId('siret')?>"
        name="<?php echo $this->getFieldName('siret')?>"
        value="<?php echo $this->htmlEscape($this->getSiret()) ?>"
        class="input-text"
        <?php echo $this->getFieldParams() ?> />
</div>