<!--
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
    //initialisation des intitulés pour table orderer
    $msgs = "{loading: '".$this->__("loading")
            ."',emptyResults: '".$this->__("emptyResults")
            ."',errorURL: '".$this->__("errorURL")
            ."',errorData: '".$this->__("errorData")
            ."',searchLabel: '".$this->__("searchLabel")
            ."',filterLabel: '".$this->__("filterLabel")
            ."',paginationOf: '".$this->__("paginationOf")
            ."',paginationPages: '".$this->__("paginationPages")
            ."',paginationFirst: '".$this->__("paginationFirst")
            ."',paginationPrev: '".$this->__("paginationPrev")
            ."',paginationNext: '".$this->__("paginationNext")
            ."',paginationLast: '".$this->__("paginationLast")."'}";
?>
<div class="std">
<div class="page-title">
    <h1>
        <?php echo $this->__('Sponsorship'); ?>
    </h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if ($this->getSponsorEnabledConfig ())://si le module parrainage est actif : affichage ?>
	<p>
    	<a href="<?php echo $this->getUrl('sponsorship_info') ?>"><?php echo $this->__('Principles of Sponsorship')?></a>
	</p>
	<p>
		<a href="<?php echo $this->getUrl('sponsorship') ?>"><?php echo $this->__('Sponsor friends')?></a>
	</p>
	<?php
	/**
	 *
	 * Invistations
	 */
	?>
	<br/>
	<h2 class="title"><?php echo $this->__('Your invitations') ?></h2>
    <?php //si l'utilisateur a des invitations en cours
        $invits = $this->getInvits();
        if ($invits):
    ?>


<div id="invit-table"></div>

<script type="text/javascript">
//<![CDATA[
invitsCols = ['<?php echo $this->__("Guest name");
            ?>','<?php echo $this->__("Guest mail");
            ?>','<?php echo $this->__("Date first invitation");
            ?>','<?php echo $this->__("Date last mail");
            ?>','<?php echo $this->__("Recall");
            ?>'];
invits = new Array(
                <?php
                    $nb = count($invits);
                    $i = 1;
                    foreach ($invits as $invit):
                        echo $this->__('{"invits_name": "%s",',htmlentities($invit["child_firstname"])." ".htmlentities($invit["child_lastname"]));
                        echo $this->__('"invits_email": "%s",',$invit["child_mail"]);
                        echo $this->__('"invits_first_date": "%s",',$this->formatDate($invit["datetime"]));
                        echo $this->__('"invits_last_mail": "%s",',$this->formatDate($invit["datetime_boost"]));
                        echo $this->__('"relance":"%s"}',"<a href='".$this->getUrl("sponsorship/boost",array("sponsorship_id"=>$invit["sponsorship_id"]))."'>".$this->__("Recall")."</a>");
                        if ($i != $nb)
                        {
                            echo ",
                                ";
                        }
                        $i++;
                    endforeach;
                ?>
    );
		<?php if ($this->isIe8() == true): ?>
invitsTable = new TableOrderer('invit-table',{data : invits, cols : invitsCols},<?php echo $this->__($msgs); ?>);
		<?php else: ?>
invitsTable = new TableOrderer('invit-table',{data : invits, cols : invitsCols, filter:'bottom', paginate:'top', pageCount:5, unsortedColumn:['relance']},<?php echo $this->__($msgs); ?>);
		<?php endif; ?>

//]]>
</script>
	<?php else : ?>
	<div>
			<?php echo $this->__("You do not have yet send invit."); ?>
	</div>
    <?php endif; //fin de vérifivcation invitations en cours?>

    <?php
	/**
	 *
	 * Filleuls
	 */
	?>
	<br/>
    <h2 class="title"><?php echo $this->__('Your godsons') ?></h2>
    <?php $_parrainages = $this->getParrainages();
    if ($_parrainages): //si l'utilisateur a déjà parrainé?>


<div id="sponsor-table"></div>

<script type="text/javascript">
sponsorshipsCols = ['<?php echo $this->__("Godson name");
            ?>','<?php echo $this->__("Sponsorship date");
            ?>','<?php echo $this->__("Last order date");
            ?>','<?php echo $this->__("Winning");
            ?>','<?php echo $this->__("Number of sponsorships");
            ?>'];
sponsorships = new Array(
                <?php
                    $nb = count($_parrainages);
                    $i = 1;
                    foreach ($_parrainages as $_parrainage):
                        $dateFDC ="";
                        if ($dateDernCde = $this->getDateDernCde ($_parrainage['entity_id'])) {
                		$dateFDC = $this->formatDate($dateDernCde);
                	}
                	else {
                		$dateFDC = "-";
                	}
                        echo $this->__('{"nom": "%s",',htmlentities($_parrainage['name']));
                        echo $this->__('"sponsorship_date": "%s",',$this->formatDate($_parrainage['created_at']));
                        echo $this->__('"last_order_date": "%s",',$dateFDC);
                        echo $this->__('"points": "%.4f",',$this->getBranchPoints ($_parrainage['entity_id']));
                        echo $this->__('"sponsorship_count":"%s"}',$this->getNbParrainages ($_parrainage['entity_id']));
                        if ($i != $nb)
                        {
                            echo ",
                                ";
                        }
                        $i++;
                    endforeach;
                ?>
    );
			<?php if ($this->isIe8() == true): ?>
			sponsorshipsTable = new TableOrderer('sponsor-table',{data : sponsorships, cols : sponsorshipsCols},<?php echo $this->__($msgs); ?>);
			<?php else: ?>
			sponsorshipsTable = new TableOrderer('sponsor-table',{data : sponsorships, cols : sponsorshipsCols, filter:'bottom', paginate:'top', pageCount:5},<?php echo $this->__($msgs); ?>);
			<?php endif; ?>
</script>
<br/>
		<?php else: //si il n'a jamais parrainé déjà parrainé ?>
		<div>
			<?php echo $this->__("You do not have active godson."); ?>
		</div>
		<?php endif; //fin verificatio si il a parrainé ?>

	<?php
	/**
	 *
	 * Points
	 */
	?>
	<br/>
            <h2>
        <?php echo $this->__('Use of your sponsorship points') ?>
            </h2>
        <div>
        <?php
            	echo $this->__('Sponsorship balance:');
            	$sPoints = floor($this->getSponsorPoints());
            	echo " ".$sPoints
        ?>
        </div>
         <!--Liste des échanges réalisés-->
        <div>
            <?php if ($this->hasChange('sponsor')):?>
            <?php
                echo $this->__("Your points exchanges:");
                $changes = $this->getChanges('sponsor');
            ?>

            <div id="sponsor-change-table"></div>

<script type="text/javascript">
sponsorshipChangesCols = ['<?php echo $this->__("Type");
            ?>','<?php echo $this->__("Date");
            ?>','<?php echo $this->__("Points");
            ?>','<?php echo $this->__("Value");
            ?>'];
sponsorshipChanges = new Array(
                <?php
                    $nb = count($changes);
                    $i = 1;
                    foreach ($changes as $change):

                        echo $this->__('{"type": "%s",',$change->getType());
                        echo $this->__('"date": "%s",',$this->formatDate($change->getDatetime()));
                        echo $this->__('"points": "%d",',$change->getPoints());
                        echo $this->__('"valeur": "%.2f"}',$change->getValue());
                        if ($i != $nb)
                        {
                            echo ",
                                ";
                        }
                        $i++;
                    endforeach;
                ?>
    );
				<?php if ($this->isIe8() == true): ?>
				new TableOrderer('sponsor-change-table',{data : sponsorshipChanges, cols : sponsorshipChangesCols},<?php echo $this->__($msgs); ?>);
				<?php else: ?>
				new TableOrderer('sponsor-change-table',{data : sponsorshipChanges, cols : sponsorshipChangesCols, filter:'bottom', paginate:'top', pageCount:5},<?php echo $this->__($msgs); ?>);
				<?php endif; ?>
</script>
            <?php endif; ?>
        </div>
        <!--Liste des échanges réalisés-->
        <?php if ($sPoints>0): //vérification du solde des points ?>
            <?php if ($this->isSponsorChangeEnabled()): //verification change actif?>
				<div>
				<?php echo $this->__('Change your points into:');?>
					<ul class="disc">
	            <?php if ($this->getSponsorCashConfig()):?>
						<li>
							<a href="<?php echo Mage::getUrl('*/*/change', Array('module'=>'sponsor','type'=>'cash')) ?>"><?php echo $this->__('Cash') ?></a>
						</li>
				<?php endif;?>
				<?php if ($this->getSponsorCouponConfig()):?>
						<li>
							<a href="<?php echo Mage::getUrl('*/*/change', Array('module'=>'sponsor','type'=>'coupon')) ?>"><?php echo $this->__('Vouchers') ?></a>
                			<?php echo $this->__(':You will receive an email with the discount code you can use on your next order.') ?>
						</li>
				<?php endif;?>
				<?php if ($this->getSponsorGiftConfig()):?>
						<li>
							<a href="<?php echo Mage::getUrl('*/*/change', Array('module'=>'sponsor','type'=>'gift')) ?>"><?php echo $this->__('Gifts') ?></a>
						</li>
				<?php endif;?>
	            	</ul>
	            </div>
            <?php endif; //change actif?>
		<?php else: //si il n'a pas de points?>
				<?php if ($this->isSponsorChangeEnabled()):?>
				<div>
					<?php echo $this->__('Once you will have points, you can change them into:');?>
				</div>
					<ul class="disc">
					<?php if ($this->getSponsorCashConfig()):?>
	            		<li>
	            		<?php echo $this->__('Cash') ?>
	            		</li>
	        		<?php endif;?>
	        		<?php if ($this->getSponsorCouponConfig()):?>
	            		<li>
	            		<?php echo $this->__('Vouchers') ?>
                    	<?php echo $this->__(':You will receive an email with the discount code you can use on your next order.') ?>
	            		</li>
	            	<?php endif;?>
	            	<?php if ($this->getSponsorGiftConfig()):?>
	            		<li>
	            		<?php echo $this->__('Gifts') ?>
	            		</li>
	            	<?php endif;?>
        			</ul>
	        	<?php endif;//change enable ?>
		<?php endif; //fin de vérification solde des points ?>
	<?php endif; //fin module parrainage enable ?>
	<div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
 </div>