<?php $product = Mage::registry('current_product'); ?>
    
<meta property="fb:app_id" content="<?php echo Mage::getStoreConfig('facebooklb/general/appid'); ?>"/>
<?php if ($product): ?>
<meta property="og:title" content="<?php echo trim($this->htmlEscape($product->getName())); ?>"/>
<meta property="og:description" content="<?php echo strip_tags($product->getDescription()); ?>" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>

<?php if($product->getTypeId() == 'bundle' && $image_bundle = Mage::getModel('bundle/product_type')->getCustomImageFromUrl(200)) : ?>
<meta property="og:image" content="<?php echo $image_bundle;?>"/>
<?php else : ?>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init(Mage::registry('current_product'), 'small_image')->resize(200);?>"/>
<?php endif; ?>
<?php endif; ?>