<?php $posts = $this->getPosts(); ?>
<?php foreach ($posts as $post): ?>
    <div class="row">
        <div class="postWrapper small-12 columns clearfix">
            <div class="postTitle">
                <h2><a href="<?php echo rtrim($post->getAddress(), '/'); ?>"><?php echo $post->getTitle(); ?></a></h2>
                <h3><?php echo Mage::helper('core')->formatDate(Mage::getModel('blog/post')->load($post->getPostId())->getCreatedTime(), 'medium', false); ?> |
                    <?php echo $this->__('Post by ').$post->getUser(); ?>
                </h3>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <div class="postDetails">
                <div class="tags">
                    <?php
                    $tags = str_replace('</li>', ',</li>',
                    $this->getTagsHtml($post));
                    $tags[strrpos($tags, ',')] = '';
                    echo $tags;
                    ?>
                </div>
                    <?php if ($this->getCommentsEnabled()): ?>
                    <div class="comments">
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $this->__('Comments') ?></a>
                    </div>
                <?php endif; ?>
                <?php
                echo $this->getLayout()->createBlock('core/template')
                    ->setData('postUrl', $post->getAddress())
                    ->setData('postTitle', $post->getTitle())
                    ->setTemplate('callouts/blog_social.phtml')->toHtml();
                ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<?php $this->getPages(); ?>
