<?php
/* @var Cartsguru_CartRecovery_Helper_Data $_helper */
$_helper = $this->helper('cartsguru_cartrecovery');
?>
<div id="cartsguru-welcome"
     class="<?php echo($_helper->isConfigured() ? 'view-success' : ($_helper->getAuthKey($_helper->getStoreFromAdmin()) ? 'view-have-account' : '')); ?>">
    <div class="header">
        <div class="inner-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <img class="cg-logo" src="<?php echo $this->getSkinUrl('images/cartsguru/logo_black.png'); ?>"/>
                    </div>
                </div>
                <div class="success-message text-center">
                    <img src="<?php echo $this->getSkinUrl('images/cartsguru/success.png'); ?>"/>
                    <h1><?= $this->__("You successfully installed Carts Guru's plugin") ?></h1>
                </div>
                <div class="no-selected-store-message text-center">
                    <h1><?= $this->__('The multistore option is enabled. If you want configure the module, please select store.') ?></h1>
                </div>

                <div class="row header-text">
                    <div class="col-lg-12">
                        <h1><?= $this->__('The best way to recover your abandoned carts') ?></h1>
                        <h2><?= $this->__('Carts Guru is the all-in-one solution to recover your abandoned carts and turn them into
                            sales. Use Emails, SMS, Automatic Calls, Facebook &amp; Instagram to convert more than 20%
                            of your lost customers into sales. ') ?></h2>
                    </div>
                </div>
                <form method="post" class="have-account-form form">
                    <?php echo $this->getBlockHtml('formkey') ?>
                    <div class="form-title"><?= $this->__('Plug Carts Guru into your Magento store') ?></div>
                    <button type="button" class="close-form-btn" onclick="cg_switchView()">
                        X
                    </button>
                    <div class="row">
                        <div class="col-md-4">
                            <input class="input full-width" value="<?php echo($_helper->getSiteId() ?: ''); ?>"
                                   name="siteid" placeholder="Site ID" required/>
                        </div>
                        <div class="col-md-4">
                            <input class="input full-width"
                                   value="<?php echo($_helper->getAuthKey($_helper->getStoreFromAdmin()) ?: ''); ?>"
                                   name="authkey" placeholder="Auth Key" required/>
                        </div>
                        <div class="col-md-4">
                            <button class="btn-full full-width" name="submitConnect"><?= $this->__('Connect it now')?></button>
                        </div>
                    </div>
                    <div class="sub-text row">
                        <div class="col-sm-12">
                            <span><?= $this->__('Don t know this information?') ?></span>
                            <a class="link" target="_blank"
                               href="https://my.carts.guru"><?= $this->__('Access it here') ?></a>
                        </div>
                    </div>
                </form>
                <form method="post" class="reset-form">
                    <?php echo $this->getBlockHtml('formkey') ?>
                    <input type="hidden" name="reset" value="1">
                    <button class="btn-text-only"
                            name="submitConnect"><?= $this->__('Reset configuration for this scope') ?></button>
                </form>
            </div>
        </div>
    </div>
    <div class="triangle-slice"></div>
    <div class="cg-footer">
        <div class="inner-section">
            <div class="container-fluid">

                <div class="success-buttons">
                    <button class="btn-not-full" onclick="cg_switchView('view-have-account', 'view-success')">Edit my
                        settings
                    </button>
                    <a href="https://my.carts.guru/?authid=<?php echo $_helper->getSiteId(); ?>&authkey=<?php echo $_helper->getAuthKey($_helper->getStoreFromAdmin()); ?>"
                       class="btn-full"><?= $this->__('Access to Carts Guru platform') ?></a>
                </div>

                <div class="try-buttons">
                    <div class="button-title"><?= $this->__('Enjoy all features during your 14-Days / $5,000 Revenue Free Trial') ?></div>
                    <button class="btn-not-full"
                            onclick="cg_switchView('view-have-account')"><?= $this->__('I have an account') ?></button>
                    <a class="btn-full"
                       href="<?php echo $this->getUrl('adminhtml/cartsguruadmin/register'); ?>"><?= $this->__('Try it
                        now for free') ?></a>
                </div>

                <div class="row">
                    <div class="list">
                        <div class="col-lg-6">
                            <div class="list-item">
                                <img src="<?php echo $this->getSkinUrl('images/cartsguru/checkmark.png'); ?>"/>
                                <span><?= $this->__('Performance-based pricing.') ?></span>
                                (<a class="link" target="_blank"
                                    href="https://carts.guru?platform=magento"><?= $this->__('see details
                                    here') ?></a>)
                            </div>
                            <div class="list-item">
                                <img src="<?php echo $this->getSkinUrl('images/cartsguru/checkmark.png'); ?>"/>
                                <span><?= $this->__('Easy-to-use, incredibly intuitive solution') ?></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="list-item">
                                <img src="<?php echo $this->getSkinUrl('images/cartsguru/checkmark.png'); ?>"/>
                                <span><?= $this->__('Run unlimited campaigns, with unlimited actions') ?></span>
                            </div>
                            <div class="list-item">
                                <img src="<?php echo $this->getSkinUrl('images/cartsguru/checkmark.png'); ?>"/>
                                <span><?= $this->__('Risk Free. No credit cards required. Cancel any time') ?></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12 text-center text-bold features-title"><?= $this->__('Features') ?></div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="channel-block-list text-center">
                            <article class="channel-block">
                                <div class="channel-title"><?= $this->__('Email retargeting') ?></div>
                                <div class="channel-picture email"></div>
                                <div class="channel-link"><?= $this->__('Learn more') ?></div>
                                <div class="channel-info">
                                    <div class="channel-block-info-triangle"></div>
                                    <p class="no-margin"><?= $this->__('Customize campaigns with your brand. Launch them at the perfect
                                        moment with automation.') ?></p>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('52%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Open rate') ?></div>
                                    </div>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('14%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Click rate') ?></div>
                                    </div>
                                </div>
                            </article>
                            <article class="channel-block">
                                <div class="channel-title"><?= $this->__('SMS retargeting') ?></div>
                                <div class="channel-picture sms"></div>
                                <div class="channel-link"><?= $this->__('Learn more') ?></div>
                                <div class="channel-info">
                                    <div class="channel-block-info-triangle"></div>
                                    <p class="no-margin"><?= $this->__('With an outstanding 97% open rate. Add SMS Marketing to your
                                        mix.') ?></p>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('20%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Conversion rate') ?></div>
                                    </div>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('1%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Unsubscription') ?></div>
                                    </div>
                                </div>
                            </article>
                            <article class="channel-block">
                                <div class="channel-title"><?= $this->__('Automatic calls') ?></div>
                                <div class="channel-picture call"></div>
                                <div class="channel-link"><?= $this->__('Learn more') ?></div>
                                <div class="channel-info">
                                    <div class="channel-block-info-triangle"></div>
                                    <p class="no-margin"><?= $this->__('Save this for your most important products and customers.
                                        Contact your customer automatically.') ?></p>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('45%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Conversion rate') ?></div>
                                    </div>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('+20%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Average cart value') ?></div>
                                    </div>
                                </div>
                            </article>
                            <article class="channel-block">
                                <div class="channel-title"><?= $this->__('Facebook &amp; Instagram') ?></div>
                                <div class="channel-picture fb"></div>
                                <div class="channel-link"><?= $this->__('Learn more') ?></div>
                                <div class="channel-info">
                                    <div class="channel-block-info-triangle"></div>
                                    <p class="no-margin"><?= $this->__('Reach your buyers where they are! Use dynamic retargeting to
                                        recover buyers with CPC ads.') ?></p>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('+34%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Click through rate') ?></div>
                                    </div>
                                    <div class="col-xs-6 channel-ef-el">
                                        <div class="channel-ef"><?= $this->__('+70%') ?></div>
                                        <div class="channel-ef-t"><?= $this->__('Prone to convert') ?></div>
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <a class="text-bold features-title" target="_blank" href="https://carts.guru?platform=magento">
                            <?= $this->__('Access Carts Guru website') ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
