<div id="form_wrapper">
  <form id="recrutement_form" name="recrutement_form" action="<?php echo $this->getUrl('recrutement/') ?>index/post" method="post">
    <fieldset>
      <input type="hidden" name="emaildest" value="<?php echo $this->getData('emaildest');?>" />
      <input type="hidden" name="poste" value="<?php echo Mage::getSingleton('cms/page')->getTitle() ?>" />
      <ul>
        <li>
          <div class="radio">
            <p class="label">Civilité <span>*</span></p>
            <input name="civilite" id="civilite_mme" type="radio" value="Mme" />
            <label for="civilite_mme">Mme <span>*</span></label>
            <input name="civilite" id="civilite_mlle" type="radio" value="Mlle" />
            <label for="civilite_mlle">Mlle <span>*</span></label>
            <input name="civilite" id="civilite_m" type="radio" value="M" checked="checked" />
            <label for="civilite_m">M. <span>*</span></label>
          </div>
        </li>
        <li>
          <div class="first">
            <label for="nom">Nom <span>*</span></label>
            <input name="nom" id="nom" type="text" class="input-text required-entry" />
          </div>
          <div>
            <label for="prenom">Prénom <span>*</span></label>
            <input name="prenom" id="prenom" type="text" class="input-text required-entry" />
          </div>
        </li>
        <li>
          <div class="first">
            <label for="adresse">Adresse <span>*</span></label>
            <input name="adresse" id="adresse" type="text" class="input-text required-entry" />
          </div>
          <div>
            <label for="complement">Complément</label>
            <input name="complement" id="complement" type="text" />
          </div>
        </li>
        <li>
          <div class="first">
            <label for="codepostal">Code Postal <span>*</span></label>
            <input name="codepostal" id="codepostal" type="text" class="input-text required-entry" />
          </div>
          <div>
            <label for="ville">Ville <span>*</span></label>
            <input name="ville" id="ville" type="text" class="input-text required-entry" />
          </div>
        </li>
        <li>
          <div class="first">
            <label for="pays">Pays</label>
            <input name="pays" id="pays" type="text" />
          </div>
          <div>
            <label for="email">E-mail <span>*</span></label>
            <input name="email" id="email" type="text" class="input-text required-entry validate-email" />
          </div>
        </li>
        <li>
          <div class="first">
            <label for="telephone">Téléphone <span>*</span></label>
            <input name="telephone" id="telephone" type="text" class="input-text required-entry" />
          </div>
          <div>
            <label for="fax">Fax</label>
            <input name="fax" id="fax" value="" type="text" />
          </div>
        </li>
      </ul>
      <ul class="files">
        <div id="queue"></div>
        <li class="first">
          <label for="file_upload_cv">Déposez votre CV <span>*</span></label>
          <input id="file_upload_cv" name="file_upload_cv" type="file" multiple="false" />
          <input id="cv" name="cv" type="hidden" class="input-text required-entry" />
        </li>
        <li>
          <label for="file_upload_lm">Déposez votre lettre de motivation<span>*</span></label>
          <input id="file_upload_lm" name="file_upload_lm" type="file" multiple="false" />
          <input id="lm" name="lm" type="hidden" class="input-text required-entry" />
        </li>
      </ul>
    </fieldset>
    <p><span class="required">*</span> Champs obligatoires</p>
    <p>Pièces jointes : extensions acceptées - pdf, doc, docx, rtf, odt ; taille maximale - 2 Mo</p>
    <div id="actions-bts"></div>
  </form>
</div>
<p id="actions-buttons"><a href="#" id="bt-postule">Je postule</a> <a href="<?php echo $this->getUrl('monbento-recrute') ?>">Retour aux offres</a></p>
<script src="<?php echo $this->getSkinUrl('js/uploadify/jquery.uploadify.min.js'); ?>" type="text/javascript"></script> 
<script type="text/javascript">
    //<![CDATA[
    	var recutementForm = new VarienForm('recrutement_form', true);
            recutementForm.submit = function(){
                    if (this.validator.validate()) {
						jQuery.ajax({
							type: "POST",
							url: '<?php echo $this->getUrl('recrutement/index/post') ?>',
							data: jQuery('#recrutement_form').serialize()
							}).done(function ( datas ) {
								var datas = jQuery.parseJSON(datas);
								if (datas.isValid) {
									var windowH = jQuery('body').outerHeight();
									var windowW = jQuery('body').outerWidth();
									var background = jQuery('<div id="background"></div>');
									var loading = jQuery('<div id="thanks"></div>');
									jQuery('body').append(background);
									jQuery('body').append(loading);
									background.css({'display': 'none','position': 'absolute','height': windowH,'width': windowW,'top': '0','left': '0','background': '#fff','z-index': '1'});
									loading.css({'display':'none','position':'absolute','background':'url(<?php echo $this->getSkinUrl('images/recrutement.png'); ?>) no-repeat','cursor':'pointer','z-index':'10','height':'374px','width':'516px','top':Math.max(0, ((jQuery(window).height() - 374) / 2) +  jQuery(window).scrollTop()) + 'px', 'left':Math.max(0, ((jQuery(window).width() - 516) / 2) + jQuery(window).scrollLeft()) + 'px'});
									background.css({"opacity" : "0.58"}).fadeIn("slow");
									loading.fadeIn("slow");		
									loading.click(function() {location.reload();});							

								}else{
									alert(datas.message);
								}
							});
                    }
            }.bind(recutementForm);
		jQuery(document).ready(function () {
			jQuery('#bt-postule').click(function(e) {	
				  jQuery('#form_wrapper').slideDown('slow', function() {
				  jQuery('#actions-bts').append(jQuery('#actions-buttons'));
				  jQuery('#bt-postule').html('Envoyer ma candidature');
					});
					jQuery(this).off('click');
					jQuery(this).click(function(e) {	
						recutementForm.submit();
				 		 e.preventDefault();
					});
				  e.preventDefault();
			});
			<?php if ($this->getData('typedemande')=='spontanee') :?>
			jQuery('#bt-postule').trigger('click');
			<?php endif;?>
		    <?php $timestamp = time();?>
			jQuery('#file_upload_cv').uploadify({
				'fileSizeLimit' : '2MB',
				'formData'     : {
					'timestamp' : '<?php echo $timestamp;?>',
					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
				},
				'height'         : '24px',
				'width'          : '240px',
				'multi'          : false,
				'fileExt'        : '*.docx;*.doc;*.pdf;*.rtf;*.odt',
				'swf'      : '<?php echo $this->getSkinUrl('js/uploadify/uploadify.swf'); ?>',
				'uploader' : '<?php echo $this->getSkinUrl('js/uploadify/uploadify.php'); ?>',
				'onUploadSuccess' : function(file, data, response) {
					if (data!='Invalid') {
					jQuery('#cv').val(data);
					jQuery('#file_upload_cv-button .uploadify-button-text').html(file.name);
					jQuery('#file_upload_cv-button .uploadify-button-text').css({'text-indent':'0','color':'#000'});
					} else{
					jQuery('#file_upload_cv-button .uploadify-button-text').html('Type de fichier invalide');
					jQuery('#file_upload_cv-button .uploadify-button-text').css({'text-indent':'0','color':'red'});
						
					}
				} 
			});
			jQuery('#file_upload_lm').uploadify({
				'fileSizeLimit' : '2MB',
				'formData'     : {
					'timestamp' : '<?php echo $timestamp;?>',
					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
				},
				'height'         : '24px',
				'width'          : '240px',
				'multi'          : false,
				'fileExt'        : '*.docx;*.doc;*.pdf;*.rtf;*.odt',
				'swf'      : '<?php echo $this->getSkinUrl('js/uploadify/uploadify.swf'); ?>',
				'uploader' : '<?php echo $this->getSkinUrl('js/uploadify/uploadify.php'); ?>',
				'onUploadSuccess' : function(file, data, response) {
					if (data!='Invalid') {
					jQuery('#lm').val(data);
					jQuery('#file_upload_lm-button .uploadify-button-text').html(file.name);
					jQuery('#file_upload_lm-button .uploadify-button-text').css({'text-indent':'0','color':'#000'});
					} else{
					jQuery('#file_upload_lm-button .uploadify-button-text').html('Type de fichier invalide');
					jQuery('#file_upload_lm-button .uploadify-button-text').css({'text-indent':'0','color':'red'});
						
					}
				} 
			});
		});
    //]]>
    </script>