<?php
/**
 * Copyright (c) 2014 GLS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    DBM
 * @package     DBM
 * @copyright   Copyright (c) 2014 GLS
 * @author 	    DBM
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="dpdfrrelais" class="c-mfp__addtobasket zoom-anim-dialog text-center mfp-hide">
    <div class="relaypoint_header">
        <label class="relaypoint_label_header"><?php echo Mage::helper('dpdfrrelais')->__('Your Pickup delivery by DPD') ?></label><br>
    </div>
    <div class="relaypoint_search">
        <div class="relaypoint_logo">
            <label class="relaypoint_label_logo"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'dpdfrance/front/relais/carrier_logo.jpg' ?>" alt=""/>
        </div>
        <div class="relaypoint_input">
            <label class="relaypoint_label_find"><?php echo Mage::helper('dpdfrrelais')->__('Find DPD Pickup points near this address : ') ?></label><br/>
            <input id="address" name="address" type="text" class="relaypoint-input-address" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>"/><br>
            <input id="zipcode" name="zipcode" type="text" class="relaypoint-input-zipcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>"/>
            <input id="city" name="city" type="text" class="relaypoint-input-city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"/>
            <button class="dpdfrbutton" onclick="fetchPoint('<?php echo substr(Mage::getUrl('dpdfrrelais/pickup/index', array('_secure' => true)), 0, -1) ?>', 'suggestion')" type="button" style="height: 20px;padding: 0;width: 36px;">
                <span>OK</span>
            </button>
            <span id="loadingpointswait" style="display:none;">
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'dpdfrance/front/relais/loader.gif' ?>" alt="" class="v-middle" />
            </span>
        </div>
        <div id="suggestion"></div>
    </div>
</div>