<h1 class="c-title--page">
    <div class="row">
        <div class="columns"><?php echo $this->__('Checkout') ?></div>
    </div>
</h1>
<script type="text/javascript">
    var deltaStepForGTM = <?php echo (Mage::getSingleton('customer/session')->isLoggedIn()) ? '2' : '1'; ?>;
</script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('oye/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('monbento/oye/accordion.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/oye/checkout/horizontal/opcheckout.js') ?>"></script>
<?php $count = count($this->getSteps()); ?>
<div id="oye-horizontal">
    <div class="c-checkout__header">
        <div class="row">
            <div class="columns">
                <ol id="checkoutSteps" <?php if($count == 5): ?> class="logged-in"<?php endif; ?>>
                	<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
                	<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
                	 <li id="step-opc-<?php echo $_stepId ?>" class="section section-header opc-<?php echo $_stepId ?><?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                	 	<div class="step-title">
                            <div class="number"><div class="o-table"><div class="o-table__cell--valignMiddle"><?php echo $i ?></div></div></div>
                            <div class="c-label"><?php echo $_stepInfo['label'] ?></div>
                            <a href="#"><?php echo $this->__('Edit') ?></a>
                        </div>
                	 
                	 </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>

    <div class="c-checkout__content">
        <div class="row">
            <div class="columns large-8 medium-10 medium-centered">
                <ol class="opc" id="checkoutStepsContent">
                    <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
                        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
                        <li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                            <ul class="opc-step-wrap">
                                <div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
                                    <?php echo $this->getChildHtml($_stepId) ?>
                                </div>
                            </ul>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var accordion = new OyeAccordion('checkoutSteps', '.step-title', true);
    accordion.setHeaders('.section .section-header');
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
<div class="c-checkout__header">
    <?php echo $this->getChildHtml('shop_reassurance') ?>
</div>
