<?php
/**
 * Copyright (c) 2014 GLS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Addonline
 * @package     Addonline_Gls
 * @copyright   Copyright (c) 2014 GLS
 * @author 	    Addonline (http://www.addonline.fr)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="layer_gls" class="layer"></div>
<?php if ($shipping_data = Mage::getSingleton('checkout/session')->getData('gls_shipping_relay_data')) : ?>
<div id='gls_relais_choisi_init' style="display: none">
	<span><?php echo $shipping_data['name'] ?></span> <span
		class='modifier_relay'><?php echo __("Change ParcelShop"); ?></span><br />
<?php echo $shipping_data['address'] ?><br />
<?php echo $shipping_data['zipcode'] ?> <?php echo $shipping_data['city'] ?></div>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[

Translator.add('Choose this ParcelShop','<?php echo __("Choose this ParcelShop"); ?>');
Translator.add('Change ParcelShop','<?php echo __("Change ParcelShop"); ?>');
Translator.add('Please provide a valide phone number.','<?php echo __("Please provide a valide mobile phone number."); ?>');
Translator.add('Please provide a valide mobile phone number.','<?php echo __("Please provide a valide mobile phone number."); ?>');

var glsBaseUrl = '<?php echo $this->getUrl('gls/ajax/') ?>';

if (aoGoToShippingMethodHooks == undefined) {
	var aoGoToShippingMethodHooks = new Array();
}
// initGlsLogos : fonction définie dans gls.js, appellée dans le hokk ci-dessous, pour charger les logos GLS 
aoGoToShippingMethodHooks[aoGoToShippingMethodHooks.length] = initGlsLogos;
if ((typeof Checkout) != "undefined") {
<?php if (version_compare(Mage::getVersion(), '1.8', '>=')) : ?>
	//On surchage la methode gotoSection de Checkout (voir opcheckout.js) : surcharge identique dans les modules addonline : socolissimo, GLS pour être compatible si on utilise les deux modules 
	Checkout.prototype.gotoSection = function (section, reloadProgressBlock) 
	{
	 		if (reloadProgressBlock) {
	            this.reloadProgressBlock(this.currentStep);
	        }
			//HOOK pour modules de livraison
	    	if (section == 'shipping_method') {
	    		for (i=0;i<aoGoToShippingMethodHooks.length;i++){
	    			aoGoToShippingMethodHooks[i]();
	    		} 
	    	}
	    	//Après le choix du mode de livraison il faut aussi recharger l'adresse de livraison car on a pu choisir un relais
			if (section == 'payment') {
	    		this.reloadProgressBlock('shipping');
	    	}
	    	this.currentStep = section;
	        var sectionElement = $('opc-' + section);
	        sectionElement.addClassName('allow');
	        this.accordion.openSection('opc-' + section);
	        if(!reloadProgressBlock) {
	            this.resetPreviousSteps();
	     }
    }
<?php else : ?>
	Checkout.prototype.gotoSection = function (section)
    {
		//HOOK pour modules de livraison
    	if (section == 'shipping_method') {
    		for (i=0;i<aoGoToShippingMethodHooks.length;i++){
    			aoGoToShippingMethodHooks[i]();
    		} 
    	}
    	//Après le choix du mode de livraison il faut aussi recharger l'adresse de livraison car on a pu choisir un relais
		if (section == 'payment') {
    		this.reloadProgressBlock('shipping');
    	}
    	var sectionElement = $('opc-'+section);
        sectionElement.addClassName('allow');
        this.accordion.openSection('opc-'+section);
        this.reloadProgressBlock(section);
    }
<?php endif; ?>    
}
//]]>
</script>
