<!--
/**
 * GLS
 *
 * @category    Addonline
 * @package     Addonline_GLS
 * @copyright   Copyright (c) 2013 GLS
 * @author 	    Addonline (http://www.addonline.fr)
 */
-->
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-tax-rate-importExport"><?php echo Mage::helper('gls')->__('Import orders') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="box-left">
        <form id="import_form" action="<?php echo $this->getUrl('*/*/import') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('gls')->__('Import orders') ?></h4>
            </div>

            <fieldset>
            <table class="form-list" cellspacing="0">
                <colgroup class="label"/>
                <colgroup class="value"/>
                <tbody>
                    <tr>
                        <td>&nbsp;</td>
                        <td class="value">
                            <?php $button_label = Mage::helper('gls')->__('Import'); ?>
                            <?php echo $this->getButtonHtml($button_label, "this.form.submit();displayLoadingMask();") ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            </fieldset>

        </form>
        <script type="text/javascript">
            var importForm = new varienForm('import_form');

            function displayLoadingMask()
            {
                var loaderArea = $$('#html-body .wrapper')[0]; // Blocks all page
                Position.clone($(loaderArea), $('loading-mask'), {offsetLeft:-2});
                toggleSelectsUnderBlock($('loading-mask'), false);
                Element.show('loading-mask');
            }
        </script>
    </div>
    <div class="clear"></div>
</div>
