<!-- 
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
$mode = Mage::helper('auguria_sponsorship/config')->getModuleMode();

if ($mode=='accumulated'):
	echo $this->getChildHtml('customer_account_accumulated_points');
else:
	if ($mode=='fidelity'
	|| $mode=='separated'):
		echo $this->getChildHtml('customer_account_fidelity_points');
	endif;	
	if ($mode=='sponsorship'
	|| $mode=='separated'):
		echo $this->getChildHtml('customer_account_sponsor_points');
	endif;
endif;