<!-- 
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
$mode = Mage::helper('auguria_sponsorship/config')->getModuleMode();
if ($mode=='accumulated'):
    $customerId = $this->getUserId();
    $customer = Mage::getModel('customer/customer')->load($customerId); 
    $nbSponsor = $this->getNbParrainages ($customerId); 
?>
<div class="box-fidelity-sponsorship">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Fidelity and sponsorship'); ?></h3><a class="c-bkg__arrow" href="<?php echo $this->getUrl('sponsorship/points/accumulated'); ?>"><?php echo $this->__('Edit')?></a>
        </div>
        <div class="box-content">
            <div>
                <span class="c-count__label"><?php echo $this->__('Fidelity and sponsorship points:') ?></span>
                <span class="c-count__int"><?php echo floor($customer->getAccumulatedPoints()); ?></span>
            </div>

            <div class="c-margin--btm">
                <span class="c-count__label"><?php echo $this->__('Active godsons:') ?></span>
                <span class="c-count__int"><?php echo $nbSponsor; ?></span>
            </div>

            <a class="c-link" href="<?php echo $this->getUrl('sponsorship') ?>"><?php echo $this->__('Sponsor friends')?></a>
        </div>
    </div>
</div>
<?php endif;?>