<!--
/**
 * @category   Auguria
 * @package    Auguria_Sponsorship
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 -->
<?php
$module = 'accumulated'; //$change['module'];
$type = 'coupon'; //$change['type'];

$t = Mage::helper('dbm_share');
$change = $this->getChange();
//$module = $change['module'];
$Module = ucfirst($module);
//$type = $change['type'];
$Type = ucfirst($type);

$getDispoPoints = 'get'.$Module.'Points';
$dPoints = $this->$getDispoPoints();

$PointsToCash = $this->getPointsToCashConfig($Module);

echo $this->__('You have %d Pépites.',$dPoints).' ';

$allowed = array();

/*
if($dPoints >= 2500)
{
    $allowed[] = array('price' =>  8, 'points' => 2500);
}

if($dPoints >= 5000)
{
    $allowed[] = array('price' =>  12, 'points' => 5000);
}

if($dPoints >= 7500)
{
    $allowed[] = array('price' =>  16, 'points' => 7500);
}*/

if($dPoints >= 200)
{
    $allowed[] = array('price' => 8, 'points' => 200);
}

?>
<?php if(count($allowed)): ?>         
<ul class="form-list">
    <?php foreach($allowed as $pointData): ?>
    <li>
        <form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="form-validate">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="club" value="<?php echo Mage::app()->getFrontController()->getRequest()->getParam('club') ?>" />
            <input type="hidden" name="module" id="module" value="<?php echo $module ?>"/>
            <input type="hidden" name="type" id="type" value="<?php echo $type ?>"/>
            <input type="hidden" name="coupon_points" value="<?php echo $pointData['points'] ?>" />
            <div class="input-box"><?php echo $t->__('You have a %s coupon (%spts)', Mage::helper('core')->currency($pointData['price'], true, false), $pointData['points']); ?></div>
            <button class="button" type="submit"><span><span><?php echo $t->__('Exchange') ?></span></span></button>
        </form>
    </li>
    <?php endforeach; ?>
    <?php /*
	<li>
		<div class="input-box">
	    	<label for="points" class="required"><em>*</em><?php echo $this->__('Points to exchange:') ?></label><br/>
	        <input onChange="pointsToCoupon('points')" type="text" name="points" id="points" value="<?php echo $this->__('%d',$dPoints) ?>" title="<?php echo $this->__('Enter the points you want to convert.') ?>" class="required-entry input-text validate-number validate-greater-than-zero"/>
	    </div>
	</li>
	<li>
	    <div class="input-box">
	    	<label for="coupon" class="required"><em>*</em><?php echo $this->__('Vouchers:') ?></label><br/>
	        <input onChange="pointsToCoupon('coupon')" type="text" name="coupon" id="coupon" value="" title="<?php echo $this->__('Indiquez la valeur du bon de réduction que vous souhaitez obtenir.') ?>" class="required-entry input-text validate-number validate-greater-than-zero"/>
	    </div>
	</li>
     <?php */ ?>
</ul>
<?php else: ?>
<br /><?php echo Mage::helper('dbm_share')->__('You do not have enough Pépites'); ?>.
<?php endif; ?>
<script type="text/javascript">
    //var dataForm = new VarienForm('form-validate', true);
</script>
