<?php

$isMobile = Mage::getModel('dbm_customer/session')->getIsMobile();

?>
<?php if(!($isMobile === true)): ?>
<div id="footer-container">
    <div id="footer" class="row small-collapse">
        <div id="footer-links" class="columns large-9">
            <div class="row large-collapse">
            <div class="bloc even columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_1')->toHtml(); ?></div>
            <div class="bloc odd columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_2')->toHtml(); ?></div>
            <div class="bloc even columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_3')->toHtml(); ?></div>
            <div class="bloc odd columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_4')->toHtml(); ?></div>
            <div class="bloc even columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_5')->toHtml(); ?></div>
            <div class="bloc odd columns small-6 medium-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_6')->toHtml(); ?></div>
            </div>
        </div>
        <div id="footer-last-column" class="columns large-3">
            <div class="row large-collapse">
                <div class="columns small-12">
                    <div id="hbar-nl" class="bloc last">
                      <?php echo $this->getChildHtml('newsletterForm'); ?>
                      <p>&nbsp;</p>
                    </div>
                    <div id="footer-social">
                            <strong><?php echo $this->__("Suivez-nous"); ?></strong>
                            <?php if (Mage::app()->getStore()->getCode() == "fr") { ?>
                            <ul class="social-buttons fr">
                                    <li><a class="twitter" href="https://twitter.com/#!/monbento_fr" target="_blank"></a></li>
                                    <li><a class="vimeo" href="https://vimeo.com/user8577348" target="_blank"></a></li>
                                    <li><a class="tumblr" href="https://monbento-france.tumblr.com/" target="_blank"></a></li>
                                    <li><a class="flickr" href="https://www.flickr.com/photos/monbento" target="_blank"></a></li>
                                    <li><a class="hellocoton" href="http://www.hellocoton.fr/mapage/monbento" target="_blank"></a></li>
                                    <li><a class="rss" href="/rss-mon-bento" target="_blank"></a></li>
                            </ul>
                            <?php } else { ?>
                            <ul class="social-buttons en">
                                    <li><a class="twitter" href="https://twitter.com/#!/monbento_world" target="_blank"></a></li>
                                    <li><a class="vimeo" href="https://vimeo.com/user8577348" target="_blank"></a></li>
                                    <li><a class="tumblr" href="https://monbento-world.tumblr.com" target="_blank"></a></li>
                                    <li><a class="flickr" href="https://www.flickr.com/photos/monbento" target="_blank"></a></li>
                                    <li><a class="rss" href="https://en.monbento.com/blog/cat/actu-mon-bento/rss" target="_blank"></a></li>
                            </ul>
                            <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div id="footer-list">
  <?php echo $this->getChildHtml('footerprodlist') ?>
	</div>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js" async="async"></script>

  <script type="text/javascript">
  //<![CDATA[
  	jQuery(function($) {
  		$('#footerprodlist').hide();
  		$('#footerprodlist').before('<a class="ferme" id="voirgamme" href="#"><?php echo $this->__("Voir toute la Gamme"); ?></a>');
  		$('#voirgamme').bind('click', function(e) {
  			if ($(this).hasClass('ouvert')) {
					$('#footerprodlist').slideUp()
					$(this).removeClass('ouvert').addClass('ferme');
					$('html, body').animate({
        			scrollTop:$(this).offset().top-150
    			}, 'slow');
  			}
  			else {
  				$('#footerprodlist').slideDown()
  				$(this).removeClass('ferme').addClass('ouvert');
  				$('html, body').animate({
        			scrollTop:$(this).offset().top-150
    			}, 'slow');
    		}
  		});
  	});
	//]]>
  </script>
</div>
<?php endif; ?>
<?php
    if(!Mage::helper('dbm_country')->isStoreHK()) {
        echo Mage::getStoreConfig('veinteractive/tags/scripttag');
    }
?>
