<?php
/**
 * Unirgy_Giftcert extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @copyright  Copyright (c) 2008 Unirgy LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @author     Boris (Moshe) Gurevich <moshe@unirgy.com>
 */
?>
<?php
/* @var $this Unirgy_Giftcert_Block_Product_Type */
$_amountConfig = $this->getAmountConfig('ugiftcert_amount_config');
$checked = isset($_amountConfig['delivery_type']) ? $_amountConfig['delivery_type'] : null;
$emailTpl = isset($_amountConfig['email_template']) ? $_amountConfig['email_template'] : $this->getProduct()->getData('ugiftcert_email_template');
$pdfTpl = isset($_amountConfig['pdf_template']) ? $_amountConfig['pdf_template'] : $this->getProduct()->getData('ugiftcert_pdf_tpl_id');

$physical = $this->getAllowPhysical();
$recipientAddressOptions = $this->getRecipientOptions();
$virtual = $this->getAllowVirtual() || ($physical == false); // we make virtual delivery the default
$senderAddressOptions = $this->getSenderOptions();

$showRecipForm = (array_search(Unirgy_Giftcert_Model_Source_Address::CUSTOM, $recipientAddressOptions) !== false);
$showSenderForm = (array_search(Unirgy_Giftcert_Model_Source_Address::CUSTOM, $senderAddressOptions) !== false);

$both = $physical && $virtual;

$addressOptions = $this->getAddressOptions();
?>
<div class="columns medium-6 c-form__col">
    <div class="form-list">
        <div class="fields">
            <div class="field">
                <label for="sender_name" class="required"><em>*</em><?php echo $this->__("From:"); ?></label>
                <div class="input-box">
                    <input type="hidden" name="email_template" id="u_email_template" value="<?php echo $emailTpl;?>" <?php echo empty($emailTpl) ? 'disabled="disabled"' : '';?>>
                    <input type="text" id="sender_name" name="sender_name" class="input-text required required-entry sender_name sender" <?php echo isset($_GET['sender_name']) ? 'value="' . $_GET['sender_name'] . '" ' : ''; ?>/>
                </div>
            </div>
            <div class="field">
                <label for="sender_email" class="required"><em>*</em><?php echo $this->__("Sender's Email Address:") ?></label>
                <div class="input-box">
                    <input type="text" id="sender_email" name="sender_email" class="input-text required required-entry validate-email sender_email sender" <?php echo isset($_GET['sender_email']) ? 'value="' . $_GET['sender_email'] . '" ' : ''; ?>/>
                </div>
            </div>
        </div>
    </div>
    <div class="form-list">
        <div class="c-title__fieldset"><?php echo $this->__('Select Amount:'); ?></div>
        <div class="fields">
            <div class="field">
                <?php echo $this->getAmountHtml($_amountConfig);?>
            </div>
        </div>
    </div>
    <div class="form-list">
        <div class="c-title__fieldset"><?php echo $this->__("Select a design :");?></div>
        <div class="fields">
            <div class="c-radio__giftCard">
                <?php $collection = Mage::getModel('ugiftcert/pdf_model')->getCollection(); ?>
                <?php $iteratorDesign = 1; foreach($collection as $template): ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($this->getProduct()->getId()); ?>
                    <?php if($img = $_product->getMediaGalleryImages()->getItemByColumnValue('label',$template->getTitle())): ?>
                    <div class="c-item">
                        <input type="radio" id="radio__0<?php echo $iteratorDesign; ?>" name="pdf_template" value="<?php echo $template->getId() ?>" data-img-src="<?php echo $_product->getMediaGalleryImages()->getItemByColumnValue('label',$template->getTitle())->getUrl() ?>" class="validate-one-required" />
                        <label for="radio__0<?php echo $iteratorDesign; ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $img->getFile())->resize(68, 43) ?>" alt="">
                        </label>
                    </div>
                    <?php endif; ?>
                <?php $iteratorDesign++; endforeach; ?>
            </div>
        </div>
    </div>
    <div class="form-list">
        <div class="fields">
            <div class="field">
                <input type="radio" name="delivery_type" id="delivery_type_virtual" value="virtual" class="delivery_type validate-one-required-by-name"<?php echo ($checked == 'virtual' || (isset($_GET['delivery_type']) && $_GET['delivery_type'] == 'virtual')) ? ' checked="checked"' : ''; ?> />
                <label for="delivery_type_virtual"><?php echo $this->__("Send gift certificate electronically"); ?></label>
            </div>
            <div class="field">
                <input type="radio" name="delivery_type" id="delivery_type_physical" value="physical" class="delivery_type validate-one-required-by-name"<?php echo ($checked == 'physical' || (isset($_GET['delivery_type']) && $_GET['delivery_type'] == 'physical') || is_null($checked)) ? ' checked="checked"' : ''; ?>>
                <label for="delivery_type_physical"><?php echo $this->__("Mail to physical address"); ?></label>
            </div>
        </div>
    </div>
</div>
<div class="columns medium-6 c-form__col" id="ugc-address-form">
    <?php if ($physical): ?>
    <div class="form-list need-myself ugc-form-item physical">
        <div class="fields">
            <div class="field">
                <input type="checkbox" name="delivery_type_myself" id="delivery_type_myself" value="write_myself"<?php echo (!isset($_GET['recipient_name']) || (isset($_GET['recipient_name']) && $_GET['recipient_name'] == $this->__("Send myself"))) ? ' checked="checked"' : ''; ?> />
                <label for="delivery_type_myself"><?php echo $this->__("Send myself"); ?></label>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <div class="form-list">
        <div class="fields">
            <div class="field">
                <label for="recipient_name" class="required"><em>*</em><?php echo $this->__("Send to:"); ?></label>
                <div class="input-box">
                    <input type="text" id="recipient_name" name="recipient_name" class="always-on recipient input-text required-entry" <?php echo (isset($_GET['recipient_name'])) ? 'value="' . $_GET['recipient_name'] . '" ' : ''; ?>/>
                </div>
            </div>
        </div>
        <?php if ($virtual): ?>
        <div class="fields ugc-form-item virtual">
            <div class="field">
                <label for="recipient_email" class="required"><em>*</em><?php echo $this->__("Recipient's Email Address:") ?></label>
                <div class="input-box">
                    <input type="text" id="recipient_email" name="recipient_email" class="input-text validate-email required recipient_email recipient required-entry" <?php echo isset($_GET['recipient_email']) ? 'value="' . $_GET['recipient_email'] . '" ' : ''; ?>/>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if ($physical): ?>
        <div class="fields ugc-form-item physical">
            <div class="field">
                <label for="recipient_address" class="required"><em>*</em><?php echo $this->__("Recipient's Mailing Address:") ?></label>
                <div class="input-box">
                    <textarea cols="10" rows="3" id="recipient_address" name="recipient_address" class="textarea required recipient_address recipient required-entry"><?php echo isset($_amountConfig['recAddr']) ? $_amountConfig['recAddr'] : ''; ?></textarea>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <?php if ($this->getAllowMessage()): ?>
    <div class="form-list">
        <div class="fields">
            <div class="field">
                <label for="recipient_message"><?php echo $this->__("Add Message:") ?></label>
                <div class="input-box">
                    <textarea class="recipient_message always-on textarea" id="recipient_message" name="recipient_message" onkeyup="processMessage(this)"><?php echo isset($_GET['recipient_message']) ? $_GET['recipient_message'] : ''; ?></textarea>
                    <?php if ($this->getMessageMaxLength()): ?>
                        <small class="accent-gray counter"><?php echo $this->__('Characters Remaining:') ?> <span
                                class="gift-card-message-length"><?php echo $this->getMessageMaxLength() ?></span>
                        </small>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <?php if (Mage::getStoreConfig('ugiftcert/email/pdf_enabled')) : ?>
    <div class="form-list">
        <div class="fields">
            <div class="field">
                <button type="button" class="button ugc-button c-button--mainBranding" id="ugc-printout-button"><span><span><?php echo $this->__("Preview PDF");?></span></span></button>
            </div>
        </div>
    </div>
    <?php endif;?>
</div>
<script type="text/javascript" src="<?php echo Mage::getDesign()->getSkinUrl('js/ugiftcert.js')?>"></script>
<script type="text/javascript">

    function processMessage(message) {
        var message = $(message);
        if (!message) {
            return;
        }

    <?php if ($this->getMessageMaxLength()): ?>
        var maxLength = <?php echo $this->getMessageMaxLength() ?>;
        var remaining = maxLength - message.value.length;
        if (remaining < 0) {
            message.value = lastValidMessage;
            remaining = maxLength - message.value.length;
        } else {
            lastValidMessage = message.value;
        }
        message.next('.counter').down('.gift-card-message-length').innerHTML = remaining;
        <?php endif; ?>

        var preview = $('gift-card-message-preview');
        preview && (preview.innerHTML = message.value.replace(/\n/g, '<br/>'));
    }

    Validation.addAllThese([
        ['validate-number-range', '<?php echo addslashes(
            $this->__('Amount is not within the specified range.')
        )?>', function (v, el) {
            var m = el.className.match(/\Wfrom-([0-9.]+)-to-([0-9.]+)\W/);
            if (!m) return true;
            v = parseNumber(v);
            return v >= m[1] && v <= m[2];
        }],

        ['validate-recipient-address', '<?php echo addslashes(
            $this->__("Please enter recipient's email or postal address")
        )?>', function (v, el) {
            var email = $(el).up('div').down('.recipient_email');
            var addr = $(el).up('div').down('.recipient_address');
            if (!$('recipient_type_someone').checked || !(email && addr)) {
                return true;
            }
            return email.value || addr.value;
        }]
    ]);


    Event.observe(window, 'load', function (e) {
        initiateDeliveryTypes();
        if (typeof ugcMultiple != 'undefined') {
            var config = {
                'tabs_container_id':'ugc-form-data',
                'add_title':'<?php echo $this->__("Add Recipient");?>',
                'recipient_label':'<?php echo $this->__("Recipient #{recipient}");?>',
                'missingContainerMsg':'<?php echo $this->__("Recipient info container not found");?>'
            };
            ugcMultiple(config);
        }

        initPdfPreview('ugc-printout-button', '<?php echo $this->getUrl('ugiftcert/customer/printout');?>');
    });
    
    Event.observe(window, 'load', function(){
            var ugAddressOptionCustom = '<?php echo Unirgy_Giftcert_Model_Source_Address::CUSTOM; ?>';
            var $recipientAddressOption = $('recipient_use_address');
            if($recipientAddressOption){
                $recipientAddressOption.observe('change', function(){
                    var self = $(this);
                    var selected = self.getValue();
                    var $container = $("ugc-address-form");
                    $container.select(".recipient").each(function (el) {
                        addressOptionsToggle(el, selected);
                    });
                });
            }
            var $senderAddressOption = $('sender_use_address');
            if($senderAddressOption){
                $senderAddressOption.observe('change', function(){
                    var self = $(this);
                    var selected = self.getValue();
                    var $container = $("ugc-address-form");
                    $container.select(".sender").each(function(el){
                        addressOptionsToggle(el, selected);
                    });
                });
            }

            function addressOptionsToggle(el, selected) {
                if (selected == ugAddressOptionCustom) {
                    $(el).enable().removeClassName("disabled");
                } else {
                    $(el).disable().addClassName("disabled")
                        .removeClassName("required-entry")
                        .removeClassName("required");
                }
            }
        });

</script>
<?php if(isset($_GET['pdf_template'])): ?>
<script type="text/javascript">
    jQuery(document).ready( function() {
        jQuery("#pdf-visuel-<?php echo $_GET['pdf_template'] ?>").click();
        jQuery("#amount").val("<?php echo $_GET['amount'] ?>");
    });
</script>
<?php endif; ?>