<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
		<?php $_iterator = 0; ?>
    <ol class="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(154); ?>" width="154" height="154" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php // Product description ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<div class="product-shop">
			    			<a href="<?php echo $_product->getProductUrl() ?>" class="more">En savoir +</a>
								<?php if($_product->isSaleable()): ?>
        				<a href="<?php echo $_product->getProductUrl() ?>?option=cart" rel="nofollow" class="btn-cart"><?php echo $this->__('Add') ?></a>
        				<?php endif; ?>
						</div>
        </li>
    <?php endforeach; ?>
    </ol>
<?php endif; ?>
