<?php 

$order = $this->getOrder();

?>
<?php if($this->isAnonOrder($order)) : ?>
    <div class="page-title">
        <h2><?php echo $this->__('Continuez votre inscription'); ?></h2>
        <p><?php echo $this->__('msg_after_guest_order'); ?></p>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
     <?php echo $this->getChildHtml('global_messages') ?> 
     <?php echo $this->getChildHtml('messages') ?> 
    <form method="post" action="<?php echo $this->getInviteRegisterUrl() ?>">
        <ul class="form-list">
            <li class="wide">
                <label for="password1"><?php echo $this->__('Mot de passe'); ?></label>
                <div class="input-box">
                    <input name="password1" type="password" />
                </div>
            </li>
            <li class="wide">
                <label for="password2"><?php echo $this->__('Confirmez votre mot de passe');?></label>
                <div class="input-box">
                    <input name="password2" type="password" />
                </div>
            </li>
            <li class="wide">
                <button type="submit" title="<?php echo $this->__('Terminer mon inscription'); ?>" class="button">
                    <span>
                        <span><?php echo $this->__('Terminer mon inscription'); ?></span>
                    </span>
                </button>
            </li>
        </ul>
    </form>
<?php endif; ?>