<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if($_product->getTypeId() == 'bundle' && $_product->getModulePersonnalisation() == 1 && $image_bundle = Mage::getModel('bundle/product_type')->getCustomImageFromUrl(332) && $image_bundle_big = Mage::getModel('bundle/product_type')->getCustomImageFromUrl(600)) : ?>
    <div class="product-image">
        <img class="hide-for-medium-down" src="<?php echo $image_bundle; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
        <img class="show-for-medium-down" src="<?php echo $image_bundle_big; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
    </div>
<?php else : ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <div class="product-image">
            <?php if (count($this->getGalleryImages()) > 0): ?>
		<div id="imageShowcase">
                    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="lightbox[rotation]" title="<?php echo $this->htmlEscape($_product->getName());?>">                            
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(600); ?>" alt="<?php if ($i <= 5) $altimage = 'alt_image_'; $altimage .= $i+1; echo strtr($_product->getData($altimage), array("\"" => "")) ;  ?>" id="productImg<?php echo $i==0?'Defaut':preg_replace('/\s+/','',$this->htmlEscape($_image->getLabel())) ?>" />
                        </a>
                    <?php $i++; endforeach; ?>
                </div>
            <?php else: ?>
                <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" rel="lightbox[rotation]" title="<?php echo $this->htmlEscape($_product->getName());?>">
                    <img class="hide-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(332); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                    <img class="show-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(600); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                </a>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img class="hide-for-medium-down" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(332).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" title="'.$this->htmlEscape($_product->getImageLabel()).'" />';
                $_img_big = '<img class="show-for-medium-down" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(600).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" title="'.$this->htmlEscape($_product->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
                echo $_helper->productAttribute($_product, $_img_big, 'image');
            ?>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0 && $_product->getTypeId() != 'ugiftcert'): ?>
<div class="more-views">
    <ul>
        <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>" rel="lightbox[rotation]" title="<?php echo $this->htmlEscape($_product->getName());?>">
                <img class="hide-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(107); ?>" alt=""/>
                <img class="show-for-medium-down" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(200); ?>" alt=""/>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
