<?php $_item = $this->getItem() ?>
<?php $productId = $_item->getProductId(); ?>
<?php $product = Mage::getModel('catalog/product')->load($productId); ?>
<?php $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility(); ?>
<?php $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM); ?>

<?php if ($product->getModulePersonnalisation() == 1 && $_options = $_item->getProduct()->getTypeInstance(true)->getOrderOptions($_item->getProduct())): ?>
    <?php $productUrl = $this->getProductUrl() . '?'; ?>
    <?php foreach ($_options['info_buyRequest']['simple_selection'] as $key => $param) : ?>
        <?php $productUrl = $productUrl == $this->getProductUrl() . '?' ? $productUrl : $productUrl . '&'; ?>
        <?php $productUrl = $productUrl . $key . '=' . $param; ?>
    <?php endforeach; ?>
    <?php $imageCustom = $this->helper('monbento_bundle')->getCustomImage($_options['info_buyRequest']['simple_selection'], 150) ?>
<?php endif; ?>
<?php $productImageLink = ($product->getModulePersonnalisation() == 1) ? $imageCustom['url'] : $this->getProductThumbnail()->resize(150);?>
<tr>
    <td class="product-cart-image">
        <?php if ($this->hasProductUrl()): ?><a href="<?php echo $productUrl ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><?php endif; ?>
            <img src="<?php echo $productImageLink; ?>" width="150" height="150" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
        <?php if ($this->hasProductUrl()): ?></a><?php endif; ?>
    </td>
    <td class="product-cart-info">
        <?php if ($this->hasProductUrl()): ?>
            <a href="<?php echo $this->getProductUrl() ?>" class="c-title"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
            <div class="c-baseline"><?php echo $_item->getProduct()->getBaseline() ?></div>
        <?php else: ?>
            <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php endif; ?>
        <?php if ($_options2 = $this->getOptionList()): ?>
            <div class="c-baseline">
                <dl class="item-options">
                    <?php if($product->getModulePersonnalisation() == 1): ?>
                        <?php $_formatedOptionValue = $this->helper('monbento_bundle')->getOptionsList($_options['info_buyRequest']['simple_selection'], $product) ?>
                        <?php $i=0;foreach ($_formatedOptionValue as $_option) : ?>
                            <dt><?php echo $this->escapeHtml($_option['name']) ?></dt>
                            <dd>
                                <?php if($_option['priceOption'] != 0) echo '+ '.Mage::helper('core')->currency($_option['priceOption']) ?>
                                <div style="clear: both;margin-left: 20px;padding-bottom: 10px;">
                                    <?php echo $_option['matiere'] ?> - <?php echo $_option['color'] ?><br>
                                </div>
                            </dd>
                        <?php $i++; endforeach; ?>
                    <?php else: ?>
                        <?php foreach ($_options2 as $_option) : ?>
                            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="truncated_full_value">
                                        <dl class="item-options">
                                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </dl>
            </div>
        <?php endif; ?>
        <?php if ($messages = $this->getMessages()): ?>
            <?php foreach ($messages as $message): ?>
                <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
    </td>
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
        <td class="a-center">
            <?php if ($isVisibleProduct): ?>
                <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
            <?php endif ?>
        </td>
    <?php endif ?>

    <?php if ($canApplyMsrp): ?>
        <td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif; ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
        </td>
    <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <td class="a-right">
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <span class="cart-price">
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                        <?php endif; ?>

                    </span>

                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
            </td>
        <?php endif; ?><!-- inclusive price starts here -->
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <td class="medium-hide product-cart-price">
                <?php $_htmlPricing = $this->getLayout()->createBlock('catalog/product_view', 'product.price', array('product_id' => $_item->getProductId())); ?>
                <?php $visuelPromo = $this->helper('monbento_site')->getProductVisuelPromo($product); ?>
                <?php if($visuelPromo == 'alt--discount' || $visuelPromo == 'alt--sales' || $visuelPromo == 'alt--order'): ?>
                    <div class="c-label--<?php echo $visuelPromo; ?>">
                        <div class="c-content"><?php echo strtolower($product->getResource()->getAttribute('visuel_promotionnel')->getSource()->getOptionText($product->getData('visuel_promotionnel'))); ?> - <?php echo $product->getMentionPromotionnelle(); ?> %</div>
                    </div>
                <?php endif; ?>
                <?php echo $_htmlPricing->getPriceHtml($_item->getProduct(), true); ?>
            </td>
        <?php endif; ?>
    <?php endif; ?>
    <td class="product-cart-actions">
        <div class="c-quantity js-form__quantity">
            <div class="c-input__button js-quantity__decrease">
                <button><span>-</span></button>
            </div>
            <div class="c-input__text">
                <input name="cart[<?php echo $_item->getId() ?>][qty]"
                    data-cart-item-id="<?php echo $this->jsQuoteEscape($_item->getSku()) ?>"
                    value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" readonly />
            </div>
            <div class="c-input__button js-quantity__increase">
                <button><span>+</span></button>
            </div>
        </div>
    </td>

    <!--Sub total starts here -->
    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
        <td class="a-right">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                <span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                    <span class="cart-price">
                    <?php endif; ?>

                    <?php if ($canApplyMsrp): ?>
                        <span class="cart-msrp-subtotal">--</span>
                    <?php else: ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?>
                        <?php else: ?>
                            <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                        <?php endif; ?>
                    <?php endif; ?>

                </span>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true); ?></span>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()); ?></span>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
        </td>
    <?php endif; ?>
    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
        <td class="product-cart-total">
            <div class="o-table">
                <div class="o-table__cell--valignMiddle">
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="c-priceBox" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                    <?php else: ?>
                        <div class="c-priceBox">
                        <?php endif; ?>

                        <?php if ($canApplyMsrp): ?>
                            <span class="cart-msrp-subtotal">--</span>
                        <?php else: ?>
                            <div class="c-price">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
                            <?php else: ?>
                                <?php echo $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                            <?php endif; ?>
                            </div>
                        <?php endif; ?>

                    </div>


                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                        <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
                            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true); ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
                                <span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </div>
        </td>
    <?php endif; ?>
    <td class="product-cart-remove">
        <div class="o-table">
            <div class="o-table__cell--valignMiddle">
                <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove item')) ?>" class="btn-remove btn-remove2"><i class="c-fonticon__icon--cross"></i></a>
            </div>
        </div>
    </td>
</tr>
