<?php
/**
 * Unirgy_Giftcert extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @copyright  Copyright (c) 2008 Unirgy LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @author     Boris (Moshe) Gurevich <moshe@unirgy.com>
 */
?>

<?php
$_full = Mage::getStoreConfig('ugiftcert/custom/cart_full_info');
$_value = $this->getTotal()->getValue();
$_gcs = explode(', ', $this->getTotal()->getGiftcertCode());
if ($_full && $_value!=0):
    $_baseBalances = explode(',', $this->getTotal()->getBaseBalances());
    $_balances = explode(',', $this->getTotal()->getBalances());
    ?>
    <?php foreach ($_gcs as $_i=>$_gc): ?>
        <div class="c-item" style="display:none;">
            <span class="c-label">
                <?php echo $_gc ?> <a class="ugiftcert-remove" href="<?php echo $this->getUrl('ugiftcert/checkout/remove', array('gc'=>$_gc)) ?>" title="<?php echo $this->__('Remove')?>"><img src="<?php echo $this->getRemoveBtnUrl() ?>" /></a>
            </span>
            <span class="c-price">
            <?php if (isset($_balances[$_i])): ?>
                <?php echo $this->helper('ugiftcert')->formatPrice(-$_balances[$_i]); ?>
            <?php endif; ?>
            </span>
        </div>
    <?php endforeach; ?>
<?php endif;?>

<div class="c-item"<?php if ($_full && $_value!=0): ?> class="tax-total" onclick="expandDetails(this, '.ugiftcert-details')"<?php endif; ?>>
    <span class="c-label">
        <?php if ($_full): ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>:
            <?php foreach ($_gcs as $_gc): ?>
                <?php echo $_gc ?> <a class="ugiftcert-remove" href="<?php echo $this->getUrl('ugiftcert/checkout/remove', array('gc'=>$_gc)) ?>" title="<?php echo $this->__('Remove')?>"><img src="<?php echo $this->getRemoveBtnUrl() ?>" /></a>
            <?php endforeach ?>
        <?php endif;?>
    </span>
    <span class="c-price"><?php echo $this->helper('ugiftcert')->formatPrice(-$_value) ?></span>
</div>
