<?php $dbmCountryHelper = Mage::helper('dbm_country'); ?>
<script type="text/javascript">
var countryConfig = JSON.parse('<?php echo $this->getCountryConfigJson(); ?>');
var langUrls = {};
var itemByList = 25;
(function($){
    var $selects = $('.dbm_country_switcher.popup .form-item select');
    
    $(document).ready(function(){

        function getCookie(name) {
            var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
            return v ? v[2] : null;
        }
        var flag_display = getCookie('<?php echo Dbm_Country_Helper_Data::COOKIE_NAME_FLAG_DISPLAY ?>');

        if (flag_display == 'yes') {
            <?php $dbmCountryHelper->setFlagDisplayCookie('no'); ?>
            <?php echo $dbmCountryHelper->printFlagDisplayCookie('no'); ?>
            $('.c-languageSwitcher .switch_link').trigger('click');
        }

        $selects.easyDropDown({
            cutOff: itemByList
        });
    });
    
    $(document).on('mousemove', '.dbm_country_switcher.popup .country.form-item .dropdown.open div', function(e){
        var $this = $(this);
        var $ul = $this.find('ul');
        var pos = e.pageY - $this.offset().top-20;
        var canvas = parseNumber($this.css('height'));
        var height = $ul.get(0).scrollHeight - canvas + 120;
        
        var newScroll = (pos * height) / canvas;
        
        $ul.css('top', -newScroll);
    });
    
    $(document).on('click', '.dbm_country_switcher.popup .country.form-item .dropdown div li',function(){
        var _select = $('#dbm_country_switch_country');
        var _li = $(this)[0]; 
        _select.find('option').each(function(){            
            if($(this)[0].innerHTML == _li.innerHTML){
                $(this).attr('selected', 'selected');
            }
        });
        _select.change();
    });
    
    $('#dbm_country_switch_country').change(function(){
        var $this = $(this);
        var val = $this.val();
        
        if(countryConfig[val])
        {
            var config = countryConfig[val];
            
            $('#dbm_country_switch_language .ajax-options').each(function(){
                $(this).remove();
            });
            
            var _baseSelect = '<select id="dbm_country_switch_language"><option value="null">-- <?php echo $this->__('Select a language');?> --</option></select>';
            $('.dbm_country_switcher.popup .language.form-item .dropdown').remove();
            $('.dbm_country_switcher.popup .language.form-item').append(_baseSelect);

            var i = 0;
            $.each(config.languages, function(key, langConfig){
                var selected = '';

                if(i == 0)
                {
                    selected = 'selected="selected"';
                }

                var html = '<option class="ajax-options" '+selected+' value="' + langConfig.url + '">' + langConfig.language + '</option>';
                $('#dbm_country_switch_language').append(html);
                i++;
            });
            var $selects = $('.dbm_country_switcher.popup .language.form-item select');
            $selects.easyDropDown({
                cutOff: itemByList
            });
        }
    });   
    
    $('.dbm_country_switcher.popup .submit .notavailable').on('click', function(){
        $('.dbm_country_switcher.popup .notavailable--content').slideDown('slow', function() {
            
        });
    });
    
    $('.dbm_country_switcher.popup .footer .back').on('click', function(){
        $('.dbm_country_switcher.popup .notavailable--content').slideUp('slow', function() {
            
        });
    });
    $('.dbm_country_switcher.popup .footer .quit').on('click', function(){
        $('.dbm_country_switcher.popup .close a').click();
        $('.dbm_country_switcher_topbar .close a').click();
    });
    
    $('.dbm_country_switcher.popup .language-switcher').on('click', function(){
        var val = $('#dbm_country_switch_language').val();
        
        if(val != 'null' ){
            if(typeof(dataLayer) != "undefined")
            {
                dataLayer.push({"event": "destination"});
            }
            document.location.href = val
        }
        return false;
    });
    
    $('.dbm_country_switcher.popup .close a').on('click', function(){
        $('.dbm_country_switcher.overlay').fadeOut('fast', function(){
            //$('.dbm_country_switcher.overlay').remove();
        });
        $('.dbm_country_switcher.popup').fadeOut('fast', function(){
            //$('.dbm_country_switcher.popup').remove();
        });
    });
    
    function setCookie(name, value, period)
    {
        var periodDate = new Date();
        periodDate.setDate(periodDate.getDate() + period);
        
        var value=escape(value) + ((periodDate==null) ? "" : "; expires="+periodDate.toUTCString());
        document.cookie=name + "=" + value;
    }
})(jQuery)
</script>
