<?php
$title = $this->getLayout()->getBlock('head')->getTitle();
$url = $this->helper('core/url')->getCurrentUrl();
?>
<div class="partage">
    <div class="title">
            <a href="#"><div class="icon"><img src="<?php echo $this->getSkinUrl('images/partage/icone.png'); ?>" /></div>
            <div class="text"><?php echo $this->__('Share spread the word');?></div></a>
    </div>
    <div class="cont-wrapper">
        <strong><?php echo $this->__('Share with your friends'); ?></strong>
        <a href="#" class="fermer"></a>
        <div class="content">
            <ul>
                <li class="even"><a href="https://www.facebook.com/share.php?u=<?php echo $url; ?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/facebook.png'); ?>" />Facebook</a></li>
                <li class="odd"><a href="https://twitter.com/share" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/twitter.png'); ?>" />Tweet</a></li>
                <li class="even"><a href="https://pinterest.com/pin/create/button/?url=<?php echo $url; ?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/pinterest.png'); ?>" />Pinterest</a></li>
                <li class="odd"><a href="https://plusone.google.com/_/+1/confirm?hl=fr&url=<?php echo $url; ?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/googleplus.png'); ?>" />Google +</a></li>
                <li class="even"><a href="https://digg.com/submit?phase=2&url=<?php echo $url; ?>" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/digg.png'); ?>" />Digg</a></li>
                <li class="odd"><a href="https://www.tumblr.com/share" target="_blank"><img src="<?php echo $this->getSkinUrl('images/partage/tumblr.png'); ?>" />Tumblr</a></li>
                <li  class="even"><a href="javascript:(function(){var w=window,l=w.location,d=w.document,s=d.createElement('script'),e=encodeURIComponent,o='object',n='AUWLBook',u='https://www.amazon.com/wishlist/add',r='readyState',T=setTimeout,a='setAttribute',g=function(){d[r]&&d[r]!='complete'?T(g,200):!w[n]?(s[a]('charset','UTF-8'),s[a]('src',u+'.js?loc='+e(l)),d.body.appendChild(s),f()):f()},f=function(){!w[n]?T(f,200):w[n].showPopover()};typeof s!=o?l.href=u+'?u='+e(l)+'&t='+e(d.title):g()}())"><img src="<?php echo $this->getSkinUrl('images/partage/amazon_wishlist.png'); ?>" />Amazon Wishlist</a></li>
                <li class="odd"><a href="https://reddit.com/submit?url=<?php echo $url; ?>&title=<?php echo $title; ?>"><img src="<?php echo $this->getSkinUrl('images/partage/reddit.png'); ?>" />Reddit</a></li>
                <li class="even last"><a href="https://del.icio.us/post?url=<?php echo $url; ?>"><img src="<?php echo $this->getSkinUrl('images/partage/delicious.png'); ?>" />Delicious</a></li>
                <li class="odd last"><a href="https://www.stumbleupon.com/submit?url=<?php echo $url; ?>&title=<?php echo $title; ?>"><img src="<?php echo $this->getSkinUrl('images/partage/stumbleupon.png'); ?>" />StumbleUpon</a></li>
            </ul>
        </div>
    </div>
</div>
<?php if (empty($GLOBALS['partage'])) { ?>
<script type="text/javascript">
  jQuery(".partage .title").live('click', function(e) {
    e.preventDefault();
    jQuery(this).parent('.partage').children('.cont-wrapper').toggle();
  });
  jQuery(".partage a.fermer").live('click', function(e) {
    e.preventDefault();
    jQuery(this).parent('.cont-wrapper').toggle();
  });
  currentUrl = '<?php echo $url; ?>';
  jQuery(".product-bundle .partage .cont-wrapper .content li a").live('click', function(e) {
	jQuery(this).attr('href',jQuery(this).attr('href').replace(currentUrl, window.location.href));
	window.open(encodeURIComponent(jQuery(this).attr('href')).replace(/%2F/g, "/").replace(/%3A/g, ":").replace(/%3F/g, "?").replace(/%3D/g, "="));
	currentUrl = window.location.href;
	return false;
  });
</script>
<?php } $GLOBALS['partage'] = true ?>
