<?php if ($this->getListRelais()) :
$i=0;
foreach ($this->getListRelais() as $relais) : ?>
<div class="point_retrait" id="point_retrait_<?php echo $i; ?>">
	<div class="distance">A <?php echo number_format ($relais->getDistance(), 2, ',', '') ?>km</div>
	<div class="point <?php echo $relais->getType() ?>"><?php if ($relais->isBureauPoste()): ?>Bureau de poste<?php elseif($relais->isCommercant()):?>Commerçant<?php elseif($relais->isCityssimo()):?>Consigne cityssimo<?php endif;?></div>
	<div class="handicap" >
	<?php if ($relais->isParking()) : ?>
		<img alt="parking dédié" src="<?php echo $this->getSkinUrl("images/socolissimo/picto_parking.jpg"); ?>" />
	<?php endif; ?>
	<?php if ($relais->isManutention()) : ?>
		<img alt="outils de manutention pour faciliter le transport du/des colis jusqu’au véhicule" src="<?php echo $this->getSkinUrl("images/socolissimo/picto_manutention.jpg"); ?>" />
	<?php endif; ?>
	<?php if ($relais->getIndicateurAcces()) : ?>
		<img alt="accessibilité aux personnes à mobilité réduite" src="<?php echo $this->getSkinUrl("images/socolissimo/picto_mobilite_reduite.jpg"); ?>" />
	<?php endif; ?>
	</div>
	<div class="adresse_point">
		<b><?php echo $relais->getLibelle() ?></b><br />
		<?php echo $relais->getAdresse() ?><br />
		<?php echo $relais->getCodePostal().' '.$relais->getCommune() ?>
	</div>
	<?php if (!$relais->getCongesTotal()) :?>
	<button type="button" class="btn_socolissimoChoisir button <?php echo $relais->getType();?>" onclick="choisirRelais('<?php echo $i; ?>')" ><span><span>Choisir <?php if ($relais->isBureauPoste()): ?>ce bureau de poste<?php elseif($relais->isCommercant()):?>ce commerçant<?php elseif($relais->isCityssimo()):?> cette consigne cityssimo<?php endif;?></span></span></button>
	<?php else :?>
        <button type="button" class="btn_socolissimoChoisir button" ><span><span>en congés</span></span></button> 	
	<?php endif;?>
</div>
<?php 
$i++;
endforeach;
endif;?>
