<?php echo $this->getChildHtml('breadcrumbs') ?>
<section class="o-section--peugeot">
    <div class="row">
        <div class="columns medium-12 medium-centered c-wrapper__header">
            <img src="<?php echo $this->getSkinUrl('proto/app/assets/media/images/c-logo--peugeot.png'); ?>" alt="Logo <?php echo $this->__('La société Peugeot Saveurs') ?>">
            <h1 class="c-title"><?php echo $this->__('about.peugeot.title') ?></h1>
        </div>
    </div>
    <div class="row">
        <div class="columns medium-12 large-6 right c-wrapper__content">
            <img src="<?php echo $this->getSkinUrl('proto/app/assets/media/images/c-img--peugeot.jpg'); ?>" alt="Monbento - <?php echo $this->__('La société Peugeot Saveurs') ?>" class="c-img">
            <div>
                <h2 class="c-title--page"><?php echo $this->__('about.peugeot.subtitle1') ?></h2>
                <p class="c-text__sofiaPro--light--20"><?php echo $this->__('about.peugeot.text1') ?></p>
                <p class="c-text__sofiaPro--light--20"><?php echo $this->__('about.peugeot.text2') ?></p>
                <a href="<?php echo $this->__('about.peugeot.button.link') ?>" alt="<?php echo $this->__('about.peugeot.button.text') ?>" class="c-button--mainBranding--arrowRightToRight" target="_blank"><?php echo $this->__('about.peugeot.button.text') ?></a>
            </div>
        </div>
    </div>
</section>