��:^<?php exit; ?>a:1:{s:7:"content";a:43:{s:18:"penci_recipe_title";a:1:{i:0;s:43:"Doigts de cantal entre-deux aux fruits secs";}s:21:"penci_recipe_preptime";a:1:{i:0;s:10:"10 minutes";}s:28:"penci_recipe_preptime_format";a:1:{i:0;s:3:"10M";}s:21:"penci_recipe_cooktime";a:1:{i:0;s:2:"0 ";}s:28:"penci_recipe_cooktime_format";a:1:{i:0;s:1:"0";}s:24:"penci_recipe_ingredients";a:1:{i:0;s:116:"4 CS de noisettes
3 CS de sésame blanc
300 g de Cantal Entre-Deux
2 CS de sauce type rouille, aïoli ou moutarde";}s:25:"penci_recipe_instructions";a:1:{i:0;s:524:"Faire griller à sec les noisettes, doucement dans une petite poêle puis les concasser.
Faire griller à sec les grains de sésame, jusqu’à ce qu’ils dorent.
Couper le Cantal en bâtonnets. Badigeonner très légèrement l’extrémité (sans croûte) de chaque bâtonnet avec une sauce puis l’enrober de noisettes ou de grains de sésame.
Réserver au froid avant de servir.

Suggestion:
Dégustez vos doigts de Cantal avec un verre de vin blanc AOC Côte d’Auvergne pour un mariage de saveurs 100% terroir.";}s:13:"_thumbnail_id";a:1:{i:0;s:5:"12107";}s:10:"_edit_lock";a:1:{i:0;s:12:"1579794787:1";}s:22:"penci_post_views_count";a:1:{i:0;s:2:"88";}s:27:"penci_post_week_views_count";a:1:{i:0;s:1:"1";}s:28:"penci_post_month_views_count";a:1:{i:0;s:2:"88";}s:23:"penci_recipe_rate_total";a:1:{i:0;s:1:"5";}s:24:"penci_recipe_rate_people";a:1:{i:0;s:1:"1";}s:12:"_wp_old_slug";a:1:{i:0;s:43:"doigts-de-cantal-entre-deux-aux-fruits-secs";}s:16:"_format_link_url";a:1:{i:0;s:0:"";}s:24:"_format_quote_source_url";a:1:{i:0;s:0:"";}s:25:"_format_quote_source_name";a:1:{i:0;s:0:"";}s:19:"_format_audio_embed";a:1:{i:0;s:0:"";}s:19:"_format_video_embed";a:1:{i:0;s:0:"";}s:10:"_edit_last";a:1:{i:0;s:1:"1";}s:8:"produits";a:1:{i:0;s:0:"";}s:9:"_produits";a:1:{i:0;s:19:"field_5d8b6efdde49c";}s:29:"_yoast_wpseo_primary_category";a:1:{i:0;s:0:"";}s:22:"_format_gallery_images";a:1:{i:0;s:6:"a:0:{}";}s:21:"penci_recipe_servings";a:1:{i:0;s:0:"";}s:17:"penci_recipe_note";a:1:{i:0;s:0:"";}s:21:"penci_recipe_calories";a:1:{i:0;s:0:"";}s:16:"penci_recipe_fat";a:1:{i:0;s:0:"";}s:21:"penci_recipe_keywords";a:1:{i:0;s:0:"";}s:20:"penci_recipe_cuisine";a:1:{i:0;s:0:"";}s:20:"penci_recipe_videoid";a:1:{i:0;s:0:"";}s:23:"penci_recipe_videotitle";a:1:{i:0;s:0:"";}s:26:"penci_recipe_videoduration";a:1:{i:0;s:0:"";}s:22:"penci_recipe_videodate";a:1:{i:0;s:0:"";}s:21:"penci_recipe_videodes";a:1:{i:0;s:0:"";}s:33:"penci_custom_sidebar_page_display";a:1:{i:0;s:0:"";}s:26:"penci_post_sidebar_display";a:1:{i:0;s:0:"";}s:18:"penci_single_style";a:1:{i:0;s:0:"";}s:27:"penci_pfeatured_image_ratio";a:1:{i:0;s:0:"";}s:28:"penci_enable_jarallax_single";a:1:{i:0;s:0:"";}s:24:"penci_post_hide_featuimg";a:1:{i:0;s:0:"";}s:26:"_yoast_wpseo_content_score";a:1:{i:0;s:2:"30";}}}